name: Deployment
on:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install package 
        run: |
          sudo apt update
          sudo apt install -y git hugo

      - uses: actions/checkout@v2

      - name: Building
        run: |
          hugo -D
          
      - name: Deploy to gh-pages
        if: ${{ !env.ACT }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
